#---------------------------------------------------------------------------------------------
# Base GCP Variables
#---------------------------------------------------------------------------------------------

variable "project_id" {
  type        = string
  description = "The ID of the project in which the resource belongs."
}

variable "host_project_id" {
  type        = string
  description = "Shared VPC Host Project"
}

variable "labels" {
  type        = map(string)
  description = "Map of GCP labels. A Data classification level must be attached to each resource using established resource labels. The business owner must choose the highest data classification level of that data that the bucket may eventually contain."
}

variable "organization_id" {
  type        = number
  description = "HCA Organization ID"
  default     = "902703590188"
}

#### IAM Variables ###

variable "service_account_id" {
  type        = string
  description = "Name that will be applied to Service Account. This is generated based on other inputs."
  default     = ""
}

#variable "dataset_id" {
#  type        = string
#  description = "BigQuery dataset ID that your scientists need to access from their Notebook. Currently this would be dataset within local project"
#  default     = ""
#}

#### Notebook Variables ###
variable "zone" {
  type        = string
  description = "Zone to launch the notebook instances in"
}

variable "machine_type" {
  type        = string
  description = "Machine type to be used for Workbench host"
}

variable "accelerator_config" {
  type = object({
    type       = string
    core_count = number
  })
  description = "The hardware accelerator used on this instance. If you use accelerators, make sure that your configuration has enough vCPUs and memory to support the machine Type you have selected."
  default     = null
}


variable "vm_image_config" {
  type = object({
    project      = string
    image_family = string
  })
  description = "Compute Engine VM image to start the notebook instance"
}

variable "instance_owner" {
  type        = string
  description = "User email to assign roles/notebooks.admin role. Example: abc123@hca.corpad.net.  Do not use gcp principal prefixes; user, group, serviceAccount"
  default     = ""
}

variable "service_account" {
  type        = string
  description = "The service account on this instance, giving access to other Google Cloud services. You must have the service account user permission to use the instance"
  default     = ""
}

variable "install_gpu_driver" {
  type        = string
  description = "Whether the end user authorizes Google Cloud to install GPU driver on this instance. If this field is empty or set to false, the GPU driver won't be installed. Only applicable to instances with GPUs."
  default     = "true"
}

variable "boot_disk_type" {
  type        = string
  description = "Possible disk types for notebook instances"
  default     = "PD_SSD"
}

variable "boot_disk_size_gb" {
  type        = number
  description = "The size of the boot disk in GB attached to this instance, up to a maximum of 64000 GB (64 TB). The minimum recommended value is 100 GB."
  default     = 200
}

variable "disk_encryption" {
  type        = string
  description = "Disk encryption method used on the boot and data disks, defaults to GMEK. Possible values are DISK_ENCRYPTION_UNSPECIFIED, GMEK, and CMEK"
  default     = ""
}

variable "no_public_ip" {
  type        = bool
  description = "No public IP will be assigned to this instance."
  default     = true
}

variable "no_proxy_access" {
  type        = bool
  description = "The notebook instance will not register with the proxy"
  default     = false
}

variable "notebook_instance_name" {
  type        = string
  description = "Name of the notebook instance.  This will be generated by other inputs"
  default     = ""
}

variable "region" {
  type        = string
  description = "Region to launch the notebook instances in"
}

variable "network" {
  type        = string
  description = "The name of the VPC that this notebook instance is in"
}

variable "subnet" {
  type        = string
  description = "The name of the subnet that this notebook instance is in"
}

variable "metadata_optional" {
  type        = map(any)
  description = "Optional Metadata for Notebooks VM instance."
  default = {
    startup-script-url        = ""
    notebook-upgrade-schedule = ""
  }
}
variable "post_startup_script" {
  type    = string
  default = ""
}
  