on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: "Select which environment's Vertex AI Pipeline we will build or promote:"
        options: 
        - Train
        - Stage
      action:
        required: true
        type: choice
        description: "Should we Build or Promote this environment's Pipeline?"
        options: 
        - "Build the environment's Pipeline"
        - "Promote this environment's Pipeline to the Next Environment"
      # environment:
      #   type: environment

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    env:
      ENV_SELECTED: ${{ inputs.environment }}"
      if: ${{ inputs.environment == 'Train' }}
        PROJECT_ID: hca-demo-dev
        JSON_FILE: vertex_pipelines/train_pipeline/json_file
        CONFIG_FILE: vertex_pipelines/train_pipeline/config_file
      if: ${{ inputs.environment == 'Stage' }}
        PROJECT_ID: armentrout-dev 
        JSON_FILE: vertex_pipelines/train_pipeline/json_file
        CONFIG_FILE: vertex_pipelines/train_pipeline/config_file
      if: ${{ inputs.action == 'Build the environment's Pipeline' }}
        #add build logic here
        ACTION: build
      if: ${{ inputs.action == 'Promote this environment's Pipeline to the Next Environment' }}
        #add promotion logic here
        ACTION: promote
    steps:
      - run: |
        echo "environment selected : $ENV_SELECTED"
        echo "Translates to Project ID: $PROJECT_ID"
        echo "Action selected : $ACTION"
        echo "json_file: $JSON_FILE"
        echo "config file: $CONFIG_FILE"

    # outputs:
    #   output1: ${{ steps.step1.outputs.* }}
    #   output2: ${{ steps.step2.outputs.* }}
    #   output3: ${{ steps.step3.outputs.* }}
    #   output4: ${{ steps.step4.outputs.* }}
    #   output5: ${{ steps.step5.outputs.* }}
      
    # steps:
    # - id: step1
    #   run: echo "environment selected : $ENV_SELECTED" >> $GITHUB_OUTPUT
    # - id: step2
    #   run: echo "Translates to Project ID: $PROJECT_ID" >> $GITHUB_OUTPUT
    # - id: step3
    #   run: echo "Action selected : $ACTION" >> $GITHUB_OUTPUT
    # - id: step4
    #   run: echo "json_file: $JSON_FILE" >> $GITHUB_OUTPUT
    # - id: step5
    #   run: echo "config file: $CONFIG_FILE" >> $GITHUB_OUTPUT

          # PROJECT_ID: $PROJECT_ID
          # ACTION: $ACTION
          # JSON_FILE: $JSON_FILE
          # CONFIG_FILE: $CONFIG_FILE